# Generated by Django 3.1.4 on 2021-08-11 04:44

from django.db import migrations, models
import short_url.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('expired_at', models.DateField(default=short_url.models.next_7_days)),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
