# Generated by Django 3.2.6 on 2021-08-11 05:14

from django.db import migrations, models
import short_url.models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=short_url.models.short_uuid, max_length=8, unique=True),
        ),
    ]
